# Generated by Django 2.1.5 on 2019-01-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
