# Generated by Django 2.1.5 on 2019-02-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='/media/default.png', upload_to='media'),
        ),
    ]
